### ISSUE TITLE
fortran wrapper type error??

### ISSUE THREAD

**Issue by Kun-Qu** [MxUI/MUI#100]
```
void mui_forget_upper_3d_f(mui_uniface_3d *uniface, double *upper, int *reset_log) {
    uniface->forget(*upper, static_cast<bool>(*reset_log));
}
```

In its fortran interface
```
    subroutine mui_forget_upper_3d_f(uniface,upper,reset_log) bind(C)
      import :: c_ptr,c_int,c_double
      type(c_ptr), intent(in), value :: uniface
      real(kind=c_double), intent(in), value :: upper
      integer(kind=c_int), intent(in), value :: reset_log
    end subroutine mui_forget_upper_3d_f
```
For arguments `upper`  and `reset_log`, is the property `value` is right? since they are pointers in cpp?

**Comment by SLongshaw** [comment]
Thanks for the issue report, I believe the current implementation is correct here - as this is using Fortran's c-bind, it is typical to prototype the called c function as a pointer and then the Fortran subroutine not. You will see the same pattern throughout the entire wrapper, with variables that are actually pointers in the c code defined as double pointers and then set as type c_ptr in the Fortran subroutine.

I'm going to close this one as I believe the current implementation is correct.

**Comment by Kun-Qu** [comment]
In the cpp code, arguments 'upper' and 'reset_log'  are the pointers.
