### ISSUE TITLE
Error in is_ready() function in uniface.h when compiling with GCC

### ISSUE THREAD

**Issue by SLongshaw** [MxUI/MUI#18]
It would seem that the first lambda statement in the is_ready() function is confusing GCC (tested up to 7.3.0), as it won't compile. It appears OK with other compilers such as Intel and IBM XL.

**Comment by yhtang** [comment]
Will take a look.

**Comment by SLongshaw** [comment]
As the fix for this bug has been reverted due to it introducing a dependency on c++14, I am re-opening this bug.

**Comment by SLongshaw** [comment]
The latest fix issues by @yhtang appears to have resolved this whilst maintaining c++11 compatibility, therefore I am closing this bug.
