### ISSUE TITLE
Setting up continuous integration server

### ISSUE THREAD

**Issue by robertsawko** [MxUI/MUI#2]
Following our conversation I would like to set up a minimal continuous integration server for us. I will do a bit of research in the coming days on the best strategy to do this.

The problem I see, straight away is that I don't want to break minimality of MUI, but any kind of testing will require to create executables. I will study now how other header only library do this. Perhaps they have a minimal Make/CMake/autoconf to create tests separately.

In one of my older projects I have tests compile as an option. If the user wanted test to compile gtest and benchmark were downloaded. This is also something to consider. @yhtang @SLongshaw please let me know if you have any thoughts on it.

Expect updates on this and a pull request from my fork.

**Comment by AlexSkillen** [comment]
@robertsawko, did you have any further thoughts on this? I've used Travis CI in the past, which is free for open-source. If everyone is happy, I can set this up, and start some minimal testing based on the ping-pong app as a starting point.

**Comment by SLongshaw** [comment]
I'm going to close this issue as it has been open for a long time with the added comment that the need for introducing CI for the library is extremely important and will be done ASAP.

Most likely this will be done using Travis CI.
