### ISSUE TITLE
Not find  the fetch_values function implement

### ISSUE THREAD

**Issue by zhangzhg0508** [MxUI/MUI#34]
Hi, I find the fetch_points function implement, but not find the fetch_values function implement.
How to implement the fetch_values  function? Thank you very much.

**Comment by SLongshaw** [comment]
Hello, this has already been implemented in my fork of the code, this, along with a few more changes, will be merged in fairly soon once things have been fully tested, in the meantime please feel free to use the version in my fork.

**Comment by zhangzhg0508** [comment]
Oh, I see. 
Thank you very much.
I would like to use the version in your fork.
