### ISSUE TITLE
Fortran wrapper test mixes comm arguments

### ISSUE THREAD

**Issue by robertsawko** [MxUI/MUI#4]
In the fortran wrapper unit test the argument taken from the command line seems to be confused. That is

``` fortran
call getarg(2, arg)
```

should probably be

``` fortran
call getarg(1, arg)
```

Also, subsequently trimming of the argument is necessary as otherwise trailing spaces confuse MPI name. That is my suggestion would be to add trim:

``` fortran
call mui_create_uniface3d_f(uniface, trim(arg))
```

This still does not fix the issue as then mpirun ends with invalid reference, which may be due to C-Fortran difficult relationship rather than MUI itself.

**Comment by SLongshaw** [comment]
I'm going to close this issue as it has been open for a long time but with the understanding that the wrappers are currently lagging behind the main library and need maintenance to bring them up to scratch ASAP.
