### ISSUE TITLE
Please, guide for how to install MUI in Lammps

### ISSUE THREAD

**Issue by conandolley103** [MxUI/MUI#63]
Dear Mr. SLongshaw

I am very beginning for simulation. Now I am studying on multiscale simulation, especially using Lammps. Hope you have time to write an instruction. Thank you very much for helping.

**Comment by SLongshaw** [comment]
Hello, I have colleagues that have done this recently.

Please find my work email address at UKRI-STFC (you can find me on the MUI About page here https://mxui.github.io/about.html under Stephen Longshaw) and send me an email, I will forward this accordingly.

Regards,

Stephen
