### ISSUE TITLE
bug in sampler_mov_avg.h

### ISSUE THREAD

**Issue by AnselGitAccount** [MxUI/MUI#7]
line 36 
point_type dx = apply( data_points[i].first - focus, abs );

change to 
point_type dx = apply( data_points[i].first - focus, fabs );

**Comment by SLongshaw** [comment]
Thank you for pointing this out, as you rightly say this could be an issue in some cases, this has been applied in the latest merge b44743cdaab1ab830147dbda0ddcd1bdf4da0103.
