### ISSUE TITLE
Better packaging for Python wrapper.

### ISSUE THREAD

**Issue by edu159** [MxUI/MUI#75]
Currently the way of building the bindings for Python is quite rudimentary through a Makefile. It would be better to create a python package the user can build and install or even upload it to The Python Package Index so the user does not need to build it at all.

**Comment by SLongshaw** [comment]
Agreed, there is no reason not to do this that I can think of

**Comment by SLongshaw** [comment]
The Python wrapper can now be built wholly through a self-contained CMake build, which can also be triggered by a top-level CMake package build process. This is a pre-cursor to releasing the library via Spack and potentially other package management systems.
