### ISSUE TITLE
Add unit tests for Python wrapper.

### ISSUE THREAD

**Issue by edu159** [MxUI/MUI#76]
There is currently no testing for the Python wrapper. Once issue #75  is dealt with and we have a python package, I propose using `pytest` as the framework to write the tests which will go under `package_name/tests` folder.

**Comment by SLongshaw** [comment]
Agreed, this can form the basis for wider testing planned for the main library and other wrappers

**Comment by edu159** [comment]
Please assign #75  and this issue to me or add me as a collaborator or the project so I can do that myself. Thanks!

**Comment by SLongshaw** [comment]
A number of self-contained unit tests have been added recently into the wrapper and various parts of the overall code, so going to close this and suggest a new issue is opened specifically around GitHub CI workflows.
