### ISSUE TITLE
Cmake shouldn't specify FORTRAN unless needed

### ISSUE THREAD

**Issue by chrisrichardson** [MxUI/MUI#91]
At the moment, the first line of `CMakeLists.txt` specifies FORTRAN (and C) as requirements.

These should be added later, inside `if(FORTRAN_WRAPPER)` e.g. using `enable_language(FORTRAN)`
Otherwise, the install will fail on systems with no fortran available...

**Comment by SLongshaw** [comment]
Thanks for finding this @chrisrichardson - it has been corrected and will be incorporated into the master and development branches and will be incorporated into the next tagged release.
