### ISSUE TITLE
Compiling Errors for MUI Python Wrapper on macOS Based Machine

### ISSUE THREAD

**Issue by Wendi-L** [MxUI/MUI#95]
Errors occur when compiling MUI Python wrapper on a macOS-based machine, even "MUI_IGNORE_ENDIAN" flag has been put on.

**Comment by Wendi-L** [comment]
1st step on this issue is to repeat it and record the behavior (error message, etc.). I'll do it in due course.

**Comment by Wendi-L** [comment]
A pull request (pull#96)[https://github.com/MxUI/MUI/pull/96] has been created by Chris on this issue.

**Comment by SLongshaw** [comment]
> A pull request [pull#96](https://github.com/MxUI/MUI/pull/96) has been created by Chris on this issue.

This has now been merged and compilation/installation tested on MacOS and Ubuntu Linux with success.

A note: there are a number of flake8 returned errors at the moment.

**Comment by SLongshaw** [comment]
Error fixed in code and flake8 issue parked (removed temporarily)
